kind: Service
apiVersion: v1
metadata:
  name: springboottest-service
  namespace: zpz665
spec:
  type: NodePort
  selector:
    app: springboottest
  ports:
  - name: springboottest-service
    protocol: TCP
    port: 80
    targetPort: 8080
